apiVersion: v1
data:
    token: ENC[AES256_GCM,data:5tWQQpyE6DlxgGt+o+jK7JxdE29uQVyvfJtbV694KrVJtvqso8AuqyX8RsJg1XaXGYfRFH5wTFxsrfQba2e42A==,iv:B8JLA1dcBUlOBAtIhUCsA97NlDCtc2/BG0xtHZBne4w=,tag:1nEaYTT9oOekzHXtxIXMKw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot2
    namespace: default
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2sa4mq6w2fg6qulpme9xvay9vlk72m743rlfy2fzu0779dnpu8qlkjjuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczlqTjR3UUhYdEdOUkVj
            WXpwVFRjYlpvaVhhTDk0NSt3VEhBbGNDdzFVCmRjdmZlTlM3UkRxV1YwN1NMaGo4
            MGh4YnhlZDlla3RTU1ZkMnJXOEordEkKLS0tIHpUZ25BNXdWTko4eXE4Z0NrVE82
            NWNoeStNWEFjbE1LYVN5MjYrbXJLU1EKlTQUe2R/KDOOt6GV2J4dWo+7GHfHTMm8
            YMVy/GIt8Sk1Q7V+DzwlamMmBdq8pGjUFWQkpTw+qVC3Y5T8prYBOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T01:41:36Z"
    mac: ENC[AES256_GCM,data:JTXRRWOG3AxL18kivfs9/R+Hqfd/CyMBsEZyaCjNHy65Wezm1cTOQhqu/3lfTE/WsBH6Anq04lFA7kyByy66CbIn1DDshBoJrNhBBPzgqoW+kbku82H3l/qIXasVkLzzPzKW/LhZIvlbOcO2iE5dsRdB1YaMdHUq00hLoNDShcE=,iv:hrlIQkNjJQ2JHa1fcz2JvDRHlnKEKG/pUIzYpMxs2Lk=,tag:nS7vo2VsKVwK5hynmonQlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
